### ISSUE TITLE
Share demo code

### ISSUE THREAD

**Issue by claytron5000** [gera2ld/react-deep-diff#2]
Would you consider sharing the demo code? I’m interested in a similar side-by-side display display. The current default display is co-nested line by line

**Comment by claytron5000** [comment]
I’ve pieced together the styling to do a side-by side, but I’m relying on n-th child selectors and generated classes (for the added/removed classes)

**Comment by gera2ld** [comment]
https://github.com/gera2ld/react-deep-diff/tree/main/src/demo
